import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-white p-[20px]">
          <Link
            href="/"
            className="mr-[10px] no-underline text-black font-bold"
          >
            Appleforum
          </Link>
          <Link href="/list" className="mr-[10px] no-underline text-black ">
            List
          </Link>
        </div>
        {children}
      </body>
    </html>
  );
}
