import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import LoginButton from "@/components/LoginButton";
import LogoutButton from "@/components/LogoutButton";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-white p-[20px]">
          <Link
            href="/"
            className="mr-[10px] no-underline text-black font-bold"
          >
            Appleforum
          </Link>
          <Link href="/list" className="mr-[10px] no-underline text-black ">
            List
          </Link>
          {session ? (
            <Link href="/write" className="mr-[10px] no-underline text-black ">
              Write
            </Link>
          ) : null}
          {session ? (
            <span>
              안녕하세요! {session.user?.name} 님 <LogoutButton />
            </span>
          ) : (
            <LoginButton />
          )}
        </div>
        {children}
      </body>
    </html>
  );
}
